# Generated by Django 5.0.3 on 2024-05-29 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_summary', models.TextField(blank=True, null=True)),
                ('data_save', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
